backend:
  name: github
  repo: krithik-khair/inkoria
  branch: main
  base_url: https://inkoria-auth.realkrithikkhair108.workers.dev
  auth_endpoint: auth
  client_id: Ov23li7NYz0oHvrzpPA7

media_folder: "images"
public_folder: "/images"

collections:
  - name: "admin_panel"
    label: "Inkoria Content"
    files:
      - label: "Books Database"
        name: "books_json"
        file: "data/books.json"
        fields:
          - label: "Books"
            name: "books"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Featured", name: "featured", widget: "boolean", default: false}
