backend:
  name: git-gateway
  branch: main

media_folder: "images/covers"
public_folder: "/images/covers"

collections:
  - name: "books"
    label: "Books"
    files:
      - label: "Books Database"
        name: "books"
        file: "data/books.json"
        fields:
          - label: "Books"
            name: "books"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Featured", name: "featured", widget: "boolean"}
